//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HistoryMark
    {
        public int Id { get; set; }
        [Required]
        public int UserId { get; set; }
        
        public System.DateTime ActionDate { get; set; }
       
        public System.TimeSpan ActionTime { get; set; }
        [Required]
        public bool Active { get; set; }
    
        public virtual User User { get; set; }
    }
}
